spring.application.name=finance-backend
server.port=8080

# H2 Database
spring.datasource.url=jdbc:h2:file:./data/financedb;AUTO_SERVER=TRUE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA / Hibernate
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=false

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JWT
app.jwt.secret=3f8a2b1c9d4e7f0a6b5c8d2e1f4a7b0c3d6e9f2a5b8c1d4e7f0a3b6c9d2e5f8
app.jwt.expiration-ms=28800000

# Swagger
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui/index.html
springdoc.swagger-ui.try-it-out-enabled=true
spring.mvc.pathmatch.use-suffix-pattern=false
server.forward-headers-strategy=framework
springdoc.swagger-ui.use-root-path=true
springdoc.swagger-ui.disable-swagger-default-url=true
# Logging
logging.level.com.finance=INFO
logging.level.org.springframework.security=WARN

logging.level.org.springframework.security.config.annotation.authentication.configuration.InitializeUserDetailsBeanManagerConfigurer=ERROR

#app.server-url=https://finance-backend-production-4aa1.up.railway.app
